using Test
using TestItems

# Correctness tests for `docs/generate_rule_catalog.jl`.  The catalog
# `docs/rule-catalog.md` is no longer committed to git (it is gitignored and
# regenerated at doc-build time by `docs/make.jl`); this test verifies that
# the generator runs without errors and produces valid, non-empty Markdown
# whose structure matches the expected catalog shape.

@testitem "rule-catalog generator: produces valid markdown from discretizations/" begin
    using EarthSciDiscretizations
    repo_root = dirname(dirname(pathof(EarthSciDiscretizations)))
    generator_path = joinpath(repo_root, "docs", "generate_rule_catalog.jl")

    @test isfile(generator_path)

    include(generator_path)

    mktempdir() do tmp
        out_path = joinpath(tmp, "rule-catalog.md")
        RuleCatalogGenerator.generate_rule_catalog(;
            catalog_dir = joinpath(repo_root, "discretizations"),
            output_path = out_path,
            repo_root = repo_root,
        )

        @test isfile(out_path)
        content = read(out_path, String)
        # Check top-level structure
        @test occursin("# EarthSciDiscretizations", content)
        @test occursin("AUTOGENERATED", content)
        @test occursin("Do not edit by hand", content)
        # Known seeded rules must appear in the catalog
        for rule_name in (
                "centered_2nd_uniform",
                "centered_2nd_uniform_vertical",
                "upwind_1st",
                "periodic_bc",
                "ppm_reconstruction",
                "weno5_advection",
            )
            @test occursin(rule_name, content)
        end
        # Both families must be present
        @test occursin("finite_difference", content)
        @test occursin("finite_volume", content)
        # Must be non-trivial (at least 1000 bytes of content)
        @test length(content) > 1000
    end
end
