using Test
using TestItems

# Drift detection for `docs/rule-catalog.md`. The catalog is autogenerated
# by `docs/generate_rule_catalog.jl` from rule files under `discretizations/`
# (the production `load_rules` discovery path). This test runs the generator
# into a temp file and byte-compares it against the in-tree catalog so any
# rule change without a regen — or any generator drift — is surfaced as a
# failed test.

@testitem "rule-catalog generator: regenerate is byte-equivalent to the in-tree catalog" begin
    using EarthSciDiscretizations
    repo_root = dirname(dirname(pathof(EarthSciDiscretizations)))
    generator_path = joinpath(repo_root, "docs", "generate_rule_catalog.jl")
    catalog_path = joinpath(repo_root, "docs", "rule-catalog.md")

    @test isfile(generator_path)
    @test isfile(catalog_path)

    include(generator_path)

    mktempdir() do tmp
        out_path = joinpath(tmp, "rule-catalog.md")
        RuleCatalogGenerator.generate_rule_catalog(;
            catalog_dir = joinpath(repo_root, "discretizations"),
            output_path = out_path,
            repo_root   = repo_root,
        )

        committed = read(catalog_path, String)
        regenerated = read(out_path, String)

        if committed != regenerated
            # Surface a localised diff to make the failure debuggable
            # without dumping 32 rows into the test log.
            commit_lines = split(committed, '\n')
            regen_lines = split(regenerated, '\n')
            @info "first 5 differing lines (committed | regenerated):"
            shown = 0
            for i in 1:min(length(commit_lines), length(regen_lines))
                commit_lines[i] == regen_lines[i] && continue
                @info "  line $i" committed=commit_lines[i] regenerated=regen_lines[i]
                shown += 1
                shown >= 5 && break
            end
            if length(commit_lines) != length(regen_lines)
                @info "line counts differ" committed=length(commit_lines) regenerated=length(regen_lines)
            end
        end

        @test committed == regenerated
    end
end
