@testsnippet LatLonConformanceSetup begin
    using Test
    using EarthSciDiscretizations
    using JSON
end

# Julia arm of the lat_lon cross-language accessor-conformance harness
# (`tests/conformance/grids/latlon/`). The sibling bindings already load the
# same `fixtures.json` + `golden/{small,realistic,reduced}.json`:
# `python/tests/test_lat_lon_conformance.py`, `rust/tests/lat_lon_conformance.rs`,
# `typescript/tests/lat_lon.conformance.test.ts`. The golden was generated by the
# Python binding (`regenerate_golden.py`) when it landed first; the Julia binding
# was tracked separately (dsc-1ts) and subsequently landed declaratively via the
# construction FAQ (esd-3we.3 / S3). `test_latlon_construction_faq.jl` pins the
# Julia FAQ output bit-for-bit against a *Julia-generated* construction golden,
# but until this @testitem there was no check that the Julia accessor runtime
# reproduces the *cross-binding* golden — i.e. that Julia ≡ Python/Rust/TypeScript.
# cartesian / vertical / arakawa each already have this arm; lat_lon was the gap
# closed by the S6 conformance audit (esd-3we.6).
#
# Geometry is closed-form (sin/cos on cell-centre latitudes), so the cross-binding
# bound `fixtures.json::tolerance.relative` (1e-14, docs/GRIDS_API.md §4.2) holds.
@testitem "lat_lon cross-language conformance" setup = [LatLonConformanceSetup] tags = [:conformance, :grid, :lat_lon] begin
    HARNESS_DIR = joinpath(@__DIR__, "..", "tests", "conformance", "grids", "latlon")
    FIXTURES = JSON.parsefile(joinpath(HARNESS_DIR, "fixtures.json"))
    REL_TOL = Float64(FIXTURES["tolerance"]["relative"])

    # Query points are 0-indexed (binding-neutral); Julia accessors are
    # 1-indexed. Convert at the test boundary so the golden remains shared.
    function close_rel(a::Real, b::Real, tol::Real)
        scale = max(1.0, abs(a), abs(b))
        return abs(a - b) <= tol * scale
    end

    function build_grid(opts)
        kw = Dict{Symbol, Any}()
        kw[:variant] = Symbol(opts["variant"])
        kw[:R] = Float64(opts["R"])
        kw[:ghosts] = Int(get(opts, "ghosts", 0))
        kw[:pole_policy] = Symbol(get(opts, "pole_policy", "none"))
        if opts["variant"] == "regular"
            kw[:nlon] = Int(opts["nlon"])
            kw[:nlat] = Int(opts["nlat"])
        else
            # reduced_gaussian: per-row longitudes (+ optional user lat_edges DATA)
            kw[:nlon_per_row] = Int[Int(x) for x in opts["nlon_per_row"]]
            haskey(opts, "lat_edges") &&
                (kw[:lat_edges] = Float64[Float64(x) for x in opts["lat_edges"]])
        end
        return EarthSciDiscretizations.grids.lat_lon(; kw...)
    end

    # Covariant/contravariant metric tensor components + Jacobian (i-independent;
    # longitudinally symmetric). `area` is the spherical-rectangle cell area.
    METRIC_NAMES = (
        :J, :g_lonlon, :g_latlat, :g_lonlat,
        :ginv_lonlon, :ginv_latlat, :ginv_lonlat,
    )
    DIR_KEYS = (:W, :E, :S, :N)

    for fixture in FIXTURES["fixtures"]
        name = fixture["name"]
        golden = JSON.parsefile(joinpath(HARNESS_DIR, "golden", "$name.json"))

        @testset "fixture=$name" begin
            grid = build_grid(fixture["opts"])
            @test n_cells(grid) == golden["n_cells"]
            @test length(fixture["query_points"]) == length(golden["cell_centers"])

            for (k, qp) in enumerate(fixture["query_points"])
                j = Int(qp[1]) + 1
                i = Int(qp[2]) + 1

                # Cell-centre geographic coordinates (lon, lat) in radians.
                (lon, lat) = cell_centers(grid, j, i)
                gc = golden["cell_centers"][k]
                @test close_rel(Float64(lon), Float64(gc["lon"]), REL_TOL)
                @test close_rel(Float64(lat), Float64(gc["lat"]), REL_TOL)

                # Face neighbours. Julia returns 1-based (j,i) tuples (or nothing
                # at a pole under pole_policy=:none); golden is 0-indexed / null.
                nb = neighbors(grid, j, i)
                for d in DIR_KEYS
                    expected = golden["neighbors_$(d)"][k]
                    got = nb[d]
                    if expected === nothing
                        @test got === nothing
                    else
                        @test got !== nothing
                        if got !== nothing
                            @test [got[1] - 1, got[2] - 1] ==
                                [Int(expected[1]), Int(expected[2])]
                        end
                    end
                end

                # Metric tensor components + Jacobian.
                for m in METRIC_NAMES
                    @test close_rel(
                        Float64(metric_eval(grid, m, j, i)),
                        Float64(golden["metric_$(m)"][k]),
                        REL_TOL,
                    )
                end

                # Spherical-rectangle cell area (== metric_eval(:area)).
                @test close_rel(
                    Float64(metric_eval(grid, :area, j, i)),
                    Float64(golden["area"][k]),
                    REL_TOL,
                )
            end
        end
    end
end
