"""Cartesian structured-grid construction via the landed M1 elementwise FAQ
path (``eval_coeff``, :mod:`earthsci_discretizations.rules`).

Python mirror of ``src/cartesian_faq.jl`` (esd-3we.1 / S1). Declarative
companion: ``discretizations/grids/cartesian/rules/cartesian_construction.esm``.
That document expresses the cartesian construction as a semiring-FAQ
(RFC ``semiring-faq-unified-ir`` §5.1/§5.2: cartesian interval index-sets +
elementwise ``arrayop`` bodies — the M1 path, NO value-invention, all CONST
cadence). It is the structured-grid analogue of the DUO value-invention path in
:mod:`earthsci_discretizations.grids.duo_topology_faq`.

This module is the thin **evaluation bridge**: it shapes a ``CartesianGrid``
into the per-axis elementwise inputs and routes every piece of grid ARITHMETIC —
the affine coordinate map, the cell-center/width derivations, and the cell-volume
product — through ESS's single AST pathway (``eval_coeff``). ESD hosts no shadow
evaluator (AGENTS.md single-pathway invariant; GRIDS_API §4.3), so the
determinism contract — and therefore the cross-binding byte-identity of the
output — lives entirely in ``earthsci_toolkit``. The only ESD-side logic is the
*structural* part: the cartesian-product flattening (column-major), the neighbor
linearization with the ``-1`` off-grid sentinel, the boundary masks, and the
identity-metric Jacobian — exactly as ``cartesian_faq.jl`` materializes those
arrays structurally while routing the arithmetic through ESS.

The FAQ is a **parallel construction oracle**: the imperative builder remains the
front-door for this bead (esd-dru, the py/rust W-step of the esd-3we structured
epic); the S5 reroute (esd-3we.5) wires it into the constructor. It is validated
byte/ULP-identical to the imperative accessors and to the committed
Julia-reference ``tests/conformance/grids/cartesian/construction/golden.json``.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..rules import eval_coeff

__all__ = ["CartesianConstruction", "cartesian_construction_faq"]


# AST nodes mirroring the equation bodies of
# ``discretizations/grids/cartesian/rules/cartesian_construction.esm``. Held as
# module consts so per-element evaluation does not rebuild the trees. The leaf
# ``i`` is the 1-based interface/cell index (binding-neutral with the Julia
# const), so a uniform edge is ``lo + (i-1)*dx``.
def _mk(op: str, *args) -> dict:
    return {"op": op, "args": list(args)}


_DX = _mk("/", _mk("-", "hi", "lo"), "n")  # (hi - lo) / n
_EDGE = _mk("+", "lo", _mk("*", _mk("-", "i", 1), "dx"))  # lo + (i - 1)*dx
_CENTER = _mk("/", _mk("+", "e_lo", "e_hi"), 2)  # (e_lo + e_hi) / 2
_WIDTH = _mk("-", "e_hi", "e_lo")  # e_hi - e_lo
_PROD = _mk("*", "a", "b")  # a * b


@dataclass(frozen=True)
class CartesianConstruction:
    """Materialized cartesian construction (mirrors the imperative trait arrays
    and the ``construction/golden.json`` contract). Per-axis arrays are lists
    indexed by axis ``d``; per-cell arrays are flattened column-major."""

    edges: list[np.ndarray]
    centers: list[np.ndarray]
    widths: list[np.ndarray]
    cell_centers: list[np.ndarray]
    cell_widths: list[np.ndarray]
    cell_volume: np.ndarray
    metric_jacobian: np.ndarray
    neighbor_minus: list[np.ndarray]
    neighbor_plus: list[np.ndarray]
    boundary_lower: list[np.ndarray]
    boundary_upper: list[np.ndarray]


def _faq_axis(
    uniform: bool, n: int, lo: float, hi: float, supplied_edges, np_dtype: type
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """One axis's ``(edges, centers, widths)`` via the M1 elementwise FAQ.

    A uniform axis is generated by the affine map ``edges[i] = lo + i*dx``
    (0-based ``i``) with ``dx = (hi - lo)/n``; a non-uniform axis takes
    ``supplied_edges`` as DATA. In both cases ``centers[i] = (edges[i] +
    edges[i+1])/2`` and ``widths[i] = edges[i+1] - edges[i]``. Every arithmetic
    step is evaluated by ESS so the result is bit-identical across bindings.
    """
    edges = np.empty(n + 1, dtype=np_dtype)
    if uniform:
        dx = eval_coeff(_DX, {"hi": float(hi), "lo": float(lo), "n": float(n)})
        for i in range(n + 1):
            edges[i] = eval_coeff(
                _EDGE, {"lo": float(lo), "i": float(i + 1), "dx": dx}
            )
    else:
        edges[:] = np.asarray(supplied_edges, dtype=np_dtype)[: n + 1]
    centers = np.empty(n, dtype=np_dtype)
    widths = np.empty(n, dtype=np_dtype)
    for i in range(n):
        b = {"e_lo": float(edges[i]), "e_hi": float(edges[i + 1])}
        centers[i] = eval_coeff(_CENTER, b)
        widths[i] = eval_coeff(_WIDTH, b)
    return edges, centers, widths


def _col_major_strides(n: tuple[int, ...]) -> list[int]:
    """Column-major strides for shape ``n`` (axis 0 fastest), matching the Julia
    ``LinearIndices`` / ``CartesianIndices`` layout."""
    s = [1] * len(n)
    for d in range(1, len(n)):
        s[d] = s[d - 1] * n[d - 1]
    return s


def cartesian_construction_faq(grid) -> CartesianConstruction:
    """Materialize a ``CartesianGrid``'s construction from the declarative FAQ,
    routing all arithmetic through the landed ESS AST evaluator (``eval_coeff``).

    Byte/ULP-identical to the imperative ``CartesianGrid`` accessors and to the
    committed Julia-reference construction golden.
    """
    np_dtype = np.dtype(grid.dtype).type
    n = tuple(int(x) for x in grid.n)
    ndim = len(n)
    nc = int(np.prod(n)) if ndim else 1
    strides = _col_major_strides(n)

    # --- per-axis elementwise FAQ (affine coords / centers / widths) ----------
    ax_edges: list[np.ndarray] = []
    ax_centers: list[np.ndarray] = []
    ax_widths: list[np.ndarray] = []
    for d in range(ndim):
        lo, hi = grid.extent[d]
        e, c, w = _faq_axis(
            bool(grid.uniform[d]), n[d], float(lo), float(hi), grid.edges[d], np_dtype
        )
        ax_edges.append(e)
        ax_centers.append(c)
        ax_widths.append(w)

    # --- per-cell flattened coordinate gathers (column-major structure) ------
    cell_centers: list[np.ndarray] = []
    cell_widths: list[np.ndarray] = []
    for d in range(ndim):
        ax_idx = (np.arange(nc) // strides[d]) % n[d]
        cell_centers.append(ax_centers[d][ax_idx])
        cell_widths.append(ax_widths[d][ax_idx])

    # --- cell_volume = product of axis widths, routed through ESS -------------
    cell_volume = np.empty(nc, dtype=np_dtype)
    for k in range(nc):
        acc = float(cell_widths[0][k])
        for d in range(1, ndim):
            acc = eval_coeff(_PROD, {"a": acc, "b": float(cell_widths[d][k])})
        cell_volume[k] = acc
    metric_jacobian = cell_volume.copy()

    # --- neighbor maps (0-based linear ids, -1 sentinel) --------------------
    def _neighbors(offset: int) -> list[np.ndarray]:
        out = []
        for d in range(ndim):
            arr = np.empty(nc, dtype=np.int64)
            for k in range(nc):
                ix = [(k // strides[p]) % n[p] for p in range(ndim)]
                new_d = ix[d] + offset
                if 0 <= new_d < n[d]:
                    lin = 0
                    for p in range(ndim):
                        coord = new_d if p == d else ix[p]
                        lin += coord * strides[p]
                    arr[k] = lin
                else:
                    arr[k] = -1
            out.append(arr)
        return out

    neighbor_minus = _neighbors(-1)
    neighbor_plus = _neighbors(+1)

    # --- boundary masks -----------------------------------------------------
    def _boundary(lower: bool) -> list[np.ndarray]:
        out = []
        for d in range(ndim):
            ax_idx = (np.arange(nc) // strides[d]) % n[d]
            out.append(ax_idx == 0 if lower else ax_idx == n[d] - 1)
        return out

    boundary_lower = _boundary(True)
    boundary_upper = _boundary(False)

    return CartesianConstruction(
        edges=ax_edges,
        centers=ax_centers,
        widths=ax_widths,
        cell_centers=cell_centers,
        cell_widths=cell_widths,
        cell_volume=cell_volume,
        metric_jacobian=metric_jacobian,
        neighbor_minus=neighbor_minus,
        neighbor_plus=neighbor_plus,
        boundary_lower=boundary_lower,
        boundary_upper=boundary_upper,
    )
