"""Cross-binding rule-eval conformance for centered_2nd_uniform_latlon.

The Julia binding is the reference evaluator (see
`docs/GRIDS_API.md` §4.3 / `src/rule_eval.jl`); the golden in
`tests/conformance/rules/centered_2nd_uniform_latlon/golden/coefficients.json`
is regenerated by
`tests/conformance/rules/centered_2nd_uniform_latlon/regenerate_golden.jl`.

This test verifies that the Python binding's `eval_coeff` and
`apply_stencil_latlon` reproduce the Julia outputs to the relative
tolerance declared in `fixtures.json` (1e-14).
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from earthsci_discretizations.rules import (
    apply_stencil_latlon,
    eval_coeff,
    load_rule,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFORMANCE_DIR = REPO_ROOT / "tests" / "conformance" / "rules" / "centered_2nd_uniform_latlon"
FIXTURES_PATH = CONFORMANCE_DIR / "fixtures.json"
GOLDEN_PATH = CONFORMANCE_DIR / "golden" / "coefficients.json"


def _selector_key(selector: dict) -> str:
    offset = int(selector["offset"])
    sign = "p" if offset >= 0 else "m"
    return f"{selector['axis']}_{sign}{abs(offset)}"


@pytest.fixture(scope="module")
def fixtures() -> dict:
    with FIXTURES_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def golden() -> dict:
    with GOLDEN_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def rule(fixtures):
    return load_rule(REPO_ROOT / fixtures["rule_path"])


def test_rule_metadata(rule):
    assert rule.name == "centered_2nd_uniform_latlon"
    assert rule.grid_family == "latlon"
    assert rule.combine == "+"
    assert len(rule.stencil) == 4
    selector_keys = {_selector_key(e.selector) for e in rule.stencil}
    assert selector_keys == {"lon_m1", "lon_p1", "lat_m1", "lat_p1"}


def test_coefficient_cases(rule, fixtures, golden):
    rtol = float(fixtures["tolerance"]["relative"])
    by_name = {c["name"]: c for c in golden["coefficient_cases"]}
    assert set(by_name) == {c["name"] for c in fixtures["coefficient_cases"]}, (
        "fixture <-> golden case names diverged; regenerate golden"
    )
    for case in fixtures["coefficient_cases"]:
        gcase = by_name[case["name"]]
        bindings = {k: float(v) for k, v in case["bindings"].items()}
        for entry in rule.stencil:
            key = _selector_key(entry.selector)
            expected = float(gcase["coefficients"][key])
            actual = eval_coeff(entry.coeff, bindings)
            assert math.isclose(actual, expected, rel_tol=rtol, abs_tol=0.0), (
                f"coefficient mismatch ({case['name']}, {key}): "
                f"python={actual!r} julia={expected!r}"
            )


def _build_field(nlat: int, nlon: int) -> tuple[np.ndarray, float, float]:
    dlon = 2.0 * math.pi / nlon
    dlat = math.pi / nlat
    lons = (np.arange(nlon) + 0.5) * dlon
    lats = -math.pi / 2.0 + (np.arange(nlat) + 0.5) * dlat
    field = np.sin(lons)[None, :] * np.cos(lats)[:, None]
    return field, dlon, dlat


def test_stencil_application(rule, fixtures, golden):
    rtol = float(fixtures["tolerance"]["relative"])
    by_name = {c["name"]: c for c in golden["stencil_cases"]}
    assert set(by_name) == {c["name"] for c in fixtures["stencil_cases"]}
    for case in fixtures["stencil_cases"]:
        gcase = by_name[case["name"]]
        nlat = int(case["grid"]["nlat"])
        nlon = int(case["grid"]["nlon"])
        R = float(case["grid"]["R"])
        field, dlon, dlat = _build_field(nlat, nlon)

        results_by_idx = {(int(r["j"]), int(r["i"])): r for r in gcase["results"]}
        for qp in case["interior_query_points"]:
            j, i = int(qp[0]), int(qp[1])
            ref = results_by_idx[(j, i)]
            cos_lat = float(ref["cos_lat"])
            bindings = {"R": R, "dlon": dlon, "dlat": dlat, "cos_lat": cos_lat}
            actual = apply_stencil_latlon(rule, field, j, i, bindings)
            expected = float(ref["result"])
            assert math.isclose(actual, expected, rel_tol=rtol, abs_tol=1e-300), (
                f"stencil result mismatch ({case['name']}, j={j}, i={i}): "
                f"python={actual!r} julia={expected!r}"
            )


def test_eval_coeff_unbound_variable_raises(rule):
    from earthsci_discretizations.rules import UnboundVariableError

    entry = rule.stencil[0]
    with pytest.raises(UnboundVariableError):
        eval_coeff(entry.coeff, {"R": 1.0, "dlon": 0.1})  # missing cos_lat


def test_apply_stencil_lat_pole_raises(rule):
    field, _, _ = _build_field(8, 16)
    bindings = {"R": 1.0, "dlon": 0.1, "dlat": 0.1, "cos_lat": 0.5}
    with pytest.raises(IndexError):
        apply_stencil_latlon(rule, field, 0, 0, bindings)
