#!/usr/bin/env python3
"""
GENERATED RULE GENERATOR — tools/fornberg_gen.py

Generates ESD uniform finite-difference stencil rules using the Fornberg (1988)
recurrence for EXACT rational weights (fractions.Fraction throughout — no float
arithmetic, no rounding).

Generated rules (all in discretizations/finite_difference/):
  1st derivative (grad), centered, uniform Cartesian:
    centered_4th_uniform.json   O(h^4)  — replaces hand-authored version
    centered_6th_uniform.json   O(h^6)  — replaces hand-authored version
    centered_8th_uniform.json   O(h^8)  — new
  2nd derivative (d2), centered, uniform Cartesian:
    centered_2nd_deriv_uniform.json  O(h^2)  — replaces hand-authored version
    centered_4th_deriv_uniform.json  O(h^4)  — new
    centered_6th_deriv_uniform.json  O(h^6)  — new
    centered_8th_deriv_uniform.json  O(h^8)  — new

Usage:
  python tools/fornberg_gen.py          # write generated rules to disk
  python tools/fornberg_gen.py --check  # verify committed files match; exit 1 on drift
"""

import argparse
import json
import sys
from fractions import Fraction
from math import gcd
from functools import reduce
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FD_DIR = REPO_ROOT / "discretizations" / "finite_difference"

_GENERATED_COMMENT = (
    "GENERATED by tools/fornberg_gen.py — do not hand-edit; edit the script + rerun"
)


# ---------------------------------------------------------------------------
# Fornberg (1988) exact-rational weight recurrence
# ---------------------------------------------------------------------------

def _fornberg_weights(z0, z, m):
    """
    Compute finite-difference weights for the m-th derivative at z0 using
    Fornberg (1988) SIAM Review, exact rational arithmetic.

    z0: int/Fraction evaluation point
    z:  list of int/Fraction stencil points (length N+1)
    m:  derivative order

    Returns a list of Fraction weights c[j] such that
        sum_j c[j] * f(z[j])  ≈  (d^m/dx^m) f(z0).
    """
    N = len(z) - 1
    zr = [Fraction(zi) for zi in z]
    z0r = Fraction(z0)

    c = [[Fraction(0)] * (N + 1) for _ in range(m + 1)]
    c[0][0] = Fraction(1)
    c1 = Fraction(1)
    c4 = zr[0] - z0r

    for n in range(1, N + 1):
        mn = min(n, m)
        c2 = Fraction(1)
        c5 = zr[n] - z0r

        # Save c[k][n-1] before the inner loop overwrites it; the last
        # assignment (for the n-th grid point) uses these "before" values.
        saved = [c[k][n - 1] for k in range(m + 1)]

        for nu in range(n):
            c3 = zr[n] - zr[nu]
            c2 *= c3
            # Iterate k from high to low so the in-place update of c[k][nu]
            # does not clobber c[k-1][nu] before it is read at k.
            for k in range(mn, -1, -1):
                ck_m1 = c[k - 1][nu] if k > 0 else Fraction(0)
                c[k][nu] = (c5 * c[k][nu] - k * ck_m1) / c3

        for k in range(mn, -1, -1):
            saved_m1 = saved[k - 1] if k > 0 else Fraction(0)
            c[k][n] = c1 * (k * saved_m1 - c4 * saved[k]) / c2

        c1 = c2
        c4 = c5

    return [c[m][j] for j in range(N + 1)]


def _lcm(a, b):
    return a * b // gcd(a, b)


def _to_integer_stencil(offsets, weights):
    """
    Given lists of offsets and Fraction weights, return (numerators, denom)
    such that weights[j] == numerators[j] / denom for all j.
    Zero-weight entries are stripped beforehand by the caller.
    """
    denom = reduce(_lcm, (w.denominator for w in weights))
    numerators = []
    for w in weights:
        scaled = w * denom
        assert scaled.denominator == 1, f"Expected integer after scaling: {scaled}"
        numerators.append(int(scaled))
    return numerators, int(denom)


# ---------------------------------------------------------------------------
# Coefficient AST builders
# ---------------------------------------------------------------------------

def _coeff_grad(num, denom):
    """JSON AST for  num / (denom * dx)."""
    if denom == 1:
        return {"op": "/", "args": [num, "dx"]}
    return {"op": "/", "args": [num, {"op": "*", "args": [denom, "dx"]}]}


def _coeff_d2(num, denom):
    """JSON AST for  num / (denom * dx * dx)."""
    dx_sq = {"op": "*", "args": ["dx", "dx"]}
    if denom == 1:
        return {"op": "/", "args": [num, dx_sq]}
    return {"op": "/", "args": [num, {"op": "*", "args": [denom, dx_sq]}]}


# ---------------------------------------------------------------------------
# Rule builders
# ---------------------------------------------------------------------------

def _build_grad_rule(accuracy_order):
    """
    Build centered grad (1st-derivative) rule JSON for the given accuracy order.
    half-width = accuracy_order // 2; zero-weight center offset is omitted.
    """
    hw = accuracy_order // 2
    z = list(range(-hw, hw + 1))
    all_weights = _fornberg_weights(0, z, 1)

    # Strip zero-weight entries (center point for 1st derivative)
    pairs = [(off, w) for off, w in zip(z, all_weights) if w != 0]
    offsets, weights = zip(*pairs)

    numerators, denom = _to_integer_stencil(list(offsets), list(weights))

    name = f"centered_{accuracy_order}th_uniform"

    stencil = []
    for off, num in zip(offsets, numerators):
        stencil.append({
            "selector": {"kind": "cartesian", "axis": "$x", "offset": off},
            "coeff": _coeff_grad(num, denom),
        })

    return {
        "discretizations": {
            name: {
                "_generated_by": _GENERATED_COMMENT,
                "applies_to": {"op": "grad", "args": ["$u"], "dim": "$x"},
                "grid_family": "cartesian",
                "combine": "+",
                "accuracy": f"O(dx^{accuracy_order})",
                "order": accuracy_order,
                "stencil": stencil,
            }
        }
    }


def _build_d2_rule(accuracy_order):
    """
    Build centered d2 (2nd-derivative) rule JSON for the given accuracy order.
    half-width = accuracy_order // 2; all center+wing offsets are included.
    """
    hw = accuracy_order // 2
    z = list(range(-hw, hw + 1))
    all_weights = _fornberg_weights(0, z, 2)

    # Include all offsets (center has non-zero weight for 2nd derivative)
    pairs = [(off, w) for off, w in zip(z, all_weights)]
    offsets, weights = zip(*pairs)

    numerators, denom = _to_integer_stencil(list(offsets), list(weights))

    if accuracy_order == 2:
        name = "centered_2nd_deriv_uniform"
    else:
        name = f"centered_{accuracy_order}th_deriv_uniform"

    stencil = []
    for off, num in zip(offsets, numerators):
        stencil.append({
            "selector": {"kind": "cartesian", "axis": "$x", "offset": off},
            "coeff": _coeff_d2(num, denom),
        })

    return {
        "discretizations": {
            name: {
                "_generated_by": _GENERATED_COMMENT,
                "applies_to": {"op": "d2", "args": ["$u"], "dim": "$x"},
                "grid_family": "cartesian",
                "combine": "+",
                "accuracy": f"O(dx^{accuracy_order})",
                "stencil": stencil,
            }
        }
    }


# ---------------------------------------------------------------------------
# All rules this script owns
# ---------------------------------------------------------------------------

def _all_rules():
    """Return list of (output_path, rule_dict) for every rule this script owns."""
    rules = []

    # 1st-derivative rules: orders 4, 6, 8
    # (centered_2nd_uniform uses the arrayop/replacement form managed separately)
    for order in [4, 6, 8]:
        name = f"centered_{order}th_uniform"
        path = FD_DIR / f"{name}.json"
        rules.append((path, _build_grad_rule(order)))

    # 2nd-derivative rules: orders 2, 4, 6, 8
    for order in [2, 4, 6, 8]:
        name = "centered_2nd_deriv_uniform" if order == 2 else f"centered_{order}th_deriv_uniform"
        path = FD_DIR / f"{name}.json"
        rules.append((path, _build_d2_rule(order)))

    return rules


def _to_json(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Main: write or check
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify committed files match generator output; exit 1 on drift.",
    )
    args = parser.parse_args()

    rules = _all_rules()
    drift_count = 0

    for path, data in rules:
        generated = _to_json(data)
        if args.check:
            if not path.exists():
                print(f"MISSING: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
                drift_count += 1
            else:
                committed = path.read_text(encoding="utf-8")
                if committed != generated:
                    print(f"DRIFT:   {path.relative_to(REPO_ROOT)}", file=sys.stderr)
                    # Print a short diff excerpt
                    committed_lines = committed.splitlines()
                    generated_lines = generated.splitlines()
                    for i, (a, b) in enumerate(
                        zip(committed_lines, generated_lines), 1
                    ):
                        if a != b:
                            print(f"  line {i}: committed={a!r}", file=sys.stderr)
                            print(f"  line {i}: generated={b!r}", file=sys.stderr)
                            break
                    else:
                        print(
                            f"  length differs: {len(committed)} vs {len(generated)}",
                            file=sys.stderr,
                        )
                    drift_count += 1
                else:
                    print(f"OK:      {path.relative_to(REPO_ROOT)}")
        else:
            path.write_text(generated, encoding="utf-8")
            print(f"Wrote:   {path.relative_to(REPO_ROOT)}")

    if args.check and drift_count > 0:
        print(
            f"\n{drift_count} file(s) differ from generator output.\n"
            "Run `python tools/fornberg_gen.py` to regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)
    elif args.check:
        print(f"All {len(rules)} generated rule files match committed JSON.")


if __name__ == "__main__":
    main()
