# Generator for `docs/rule-catalog.md`.
#
# Walks every rule file under `discretizations/` via the production
# `EarthSciDiscretizations.load_rules` path (the same discovery the walker
# harness uses, see `test/walk_esd_tests.jl:44-47`), parses each JSON, and
# emits a Markdown manifest organised by scheme family.
#
# Invoked from `docs/make.jl` so the catalog is regenerated on every doc
# build. Can also be run standalone:
#
#   julia --project=docs docs/generate_rule_catalog.jl
#
# The output file is autogenerated; do not hand-edit it. Curated planning
# prose that predates this generator lives in `docs/rule-catalog-roadmap.md`
# and remains hand-maintained until a follow-up bead migrates it.

module RuleCatalogGenerator

using EarthSciDiscretizations: load_rules, RuleFile
using JSON

export generate_rule_catalog

const FAMILY_HEADINGS = Dict(
    :finite_difference => "Finite-difference rules",
    :finite_volume => "Finite-volume rules",
    :spectral => "Spectral rules",
    :grids => "Grid family schemas",
)

# A single row in the catalog. One row corresponds to one inner rule key
# inside one rule file (in practice every file has exactly one inner key).
struct CatalogRow
    family::Symbol
    file_stem::String          # filename stem from RuleFile.name
    rule_key::String           # inner key (e.g. "centered_2nd_uniform")
    shape::String              # "discretizations", "rules", or "schema"
    op::String                 # applies_to.op / pattern.op / "—"
    grid_family::String
    accuracy::String
    reference::String          # one-line citation, truncated
    rel_path::String           # path relative to repo root
end

# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------

"""
    catalog_rows(catalog_dir; repo_root) -> Vector{CatalogRow}

Discover rule files under `catalog_dir` via `load_rules` and reduce each one
to a `CatalogRow`. `repo_root` is used to make paths repo-relative.
"""
function catalog_rows(catalog_dir::AbstractString; repo_root::AbstractString)
    rules = load_rules(catalog_dir)
    rows = CatalogRow[]
    for rf in rules
        try
            body = JSON.parsefile(rf.path)
            append!(rows, _rows_for_file(rf, body; repo_root = repo_root))
        catch err
            # Surface parse errors as catalog rows rather than blowing up the
            # doc build; a malformed rule file should be visible in the
            # catalog as a parse error, not silently dropped.
            push!(
                rows, CatalogRow(
                    rf.family, rf.name, rf.name, "parse_error",
                    "—", "—", "—", "PARSE ERROR: $(err)",
                    _relpath(rf.path, repo_root),
                )
            )
        end
    end
    return rows
end

function _rows_for_file(rf::RuleFile, body; repo_root)
    if haskey(body, "discretizations")
        # Sort inner keys for deterministic output (JSON.jl returns an
        # unordered Dict; we want the catalog to be reproducible regardless
        # of hash insertion order).
        return [
            _row_for_inner(
                    rf, k, body["discretizations"][k],
                    "discretizations"; repo_root = repo_root
                )
                for k in sort!(collect(keys(body["discretizations"])))
        ]
    elseif haskey(body, "rules")
        return [
            _row_for_inner(
                    rf, k, body["rules"][k],
                    "rules"; repo_root = repo_root
                )
                for k in sort!(collect(keys(body["rules"])))
        ]
    elseif haskey(body, "family") && haskey(body, "options")
        # grid-family schema (e.g. discretizations/grids/cartesian.schema.json)
        return [
            CatalogRow(
                rf.family, rf.name, String(get(body, "family", rf.name)),
                "schema",
                "—",
                String(get(body, "family", "—")),
                String(get(body, "version", "—")),
                "Grid family schema (required: " *
                    join(get(body, "required", String[]), ", ") * ")",
                _relpath(rf.path, repo_root),
            ),
        ]
    else
        return [
            CatalogRow(
                rf.family, rf.name, rf.name, "unknown",
                "—", "—", "—",
                "Unrecognised rule shape (top keys: " *
                    join(sort(collect(keys(body))), ", ") * ")",
                _relpath(rf.path, repo_root),
            ),
        ]
    end
end

function _row_for_inner(rf::RuleFile, key, def, shape; repo_root)
    op = "—"
    if shape == "discretizations"
        applies = get(def, "applies_to", nothing)
        if applies isa AbstractDict && haskey(applies, "op")
            op = String(applies["op"])
        end
    elseif shape == "rules"
        pat = get(def, "pattern", nothing)
        if pat isa AbstractDict && haskey(pat, "op")
            op = String(pat["op"])
        end
    end
    grid_family = String(
        get(
            def, "grid_family",
            get(def, "region", "—")
        )
    )
    accuracy = String(get(def, "accuracy", "—"))
    reference = _short_reference(def)
    return CatalogRow(
        rf.family, rf.name, String(key), shape,
        op, grid_family, accuracy, reference,
        _relpath(rf.path, repo_root),
    )
end

function _short_reference(def)
    for k in ("reference", "schema_notes", "composition_hint")
        v = get(def, k, nothing)
        v isa AbstractString || continue
        return _truncate_one_line(v)
    end
    return "—"
end

function _truncate_one_line(s::AbstractString; limit::Int = 200)
    one_line = replace(String(s), r"\s+" => " ")
    one_line = replace(one_line, "|" => "\\|")  # keep tables intact
    if length(one_line) > limit
        return first(one_line, limit) * "…"
    end
    return one_line
end

function _relpath(path::AbstractString, repo_root::AbstractString)
    p = abspath(path)
    r = abspath(repo_root)
    if startswith(p, r)
        return lstrip(p[(length(r) + 1):end], '/')
    end
    return p
end

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

function render_catalog(io::IO, rows::Vector{CatalogRow}; catalog_dir, repo_root)
    println(io, "# EarthSciDiscretizations — Rule Catalog")
    println(io)
    println(
        io, "<!-- AUTOGENERATED by `docs/generate_rule_catalog.jl`. ",
        "Do not edit by hand — regenerate from `discretizations/` instead. -->"
    )
    println(io)
    println(
        io, "Authoritative manifest of every discretization rule and grid-family ",
        "schema currently committed under `$(_relpath(catalog_dir, repo_root))`. ",
        "Each row corresponds to one inner rule key inside one JSON file, as ",
        "discovered via `EarthSciDiscretizations.load_rules` — the same ",
        "production path the walker harness uses for rule discovery."
    )
    println(io)
    println(
        io, "Hand-authored planning prose (aspirational rules not yet committed, ",
        "audit lenses, and source-by-source roadmaps) is preserved in ",
        "[`rule-catalog-roadmap.md`](rule-catalog-roadmap.md) ",
        "until a follow-up bead migrates that content into a ",
        "generated form."
    )
    println(io)

    println(io, "## Header metadata")
    println(io)
    println(io, "| Field | Value |")
    println(io, "|---|---|")
    println(io, "| Generator | `docs/generate_rule_catalog.jl` |")
    println(io, "| Catalog root | `$(_relpath(catalog_dir, repo_root))` |")
    println(io, "| Total rule entries | $(length(rows)) |")
    println(
        io, "| Families discovered | ",
        join(sort(unique(string.(getfield.(rows, :family)))), ", "), " |"
    )
    println(io)

    println(io, "## Counts by family")
    println(io)
    println(io, "| Family | Entries |")
    println(io, "|---|---:|")
    for fam in sort(unique(getfield.(rows, :family)); by = string)
        n = count(r -> r.family == fam, rows)
        println(io, "| `$(string(fam))` | $n |")
    end
    println(io)

    println(io, "## How to read this catalog")
    println(io)
    println(io, "Columns:")
    println(io)
    println(io, "| Column | Meaning |")
    println(io, "|---|---|")
    println(io, "| `name` | Inner rule key (`discretizations.<name>` or `rules.<name>`). Usually matches the filename stem. |")
    println(io, "| `shape` | `discretizations` (stencil/replacement rule), `rules` (index-rewrite / boundary-condition rule), `schema` (grid-family schema), `unknown`/`parse_error` (diagnostic). |")
    println(io, "| `op` | `applies_to.op` for stencil rules, or `pattern.op` for index-rewrite rules. The mathematical operator each rule discretizes. |")
    println(io, "| `grid_family` | The rule's declared `grid_family` field, or the region for index-rewrite rules. |")
    println(io, "| `accuracy` | Truncation order or accuracy claim from the rule, verbatim. |")
    println(io, "| `reference` | One-line citation derived from `reference` / `schema_notes` / `composition_hint` (truncated). |")
    println(io, "| `path` | Repo-relative path to the JSON file. |")
    println(io)

    for fam in sort(unique(getfield.(rows, :family)); by = string)
        heading = get(FAMILY_HEADINGS, fam, "Family `$(string(fam))`")
        println(io, "## $(heading) (`$(string(fam))`)")
        println(io)
        println(io, "| name | shape | op | grid_family | accuracy | reference | path |")
        println(io, "|---|---|---|---|---|---|---|")
        fam_rows = sort(filter(r -> r.family == fam, rows); by = r -> r.rule_key)
        for r in fam_rows
            println(
                io, "| `$(r.rule_key)` | $(r.shape) | `$(r.op)` | ",
                "$(r.grid_family) | $(r.accuracy) | $(r.reference) | ",
                "`$(r.rel_path)` |"
            )
        end
        println(io)
    end

    return nothing
end

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

"""
    generate_rule_catalog(; catalog_dir, output_path, repo_root)

Regenerate `output_path` (Markdown) from rule files under `catalog_dir`.
`repo_root` is used to render repo-relative paths in the catalog.

Returns the absolute output path.
"""
function generate_rule_catalog(;
        catalog_dir::AbstractString,
        output_path::AbstractString,
        repo_root::AbstractString = dirname(catalog_dir)
    )
    rows = catalog_rows(catalog_dir; repo_root = repo_root)
    open(output_path, "w") do io
        render_catalog(io, rows; catalog_dir = catalog_dir, repo_root = repo_root)
    end
    return abspath(output_path)
end

end # module RuleCatalogGenerator
