"""
    cartesian_faq.jl — cartesian structured-grid construction via the landed M1
    elementwise FAQ path (`EarthSciSerialization` AST evaluator).

Declarative companion: `discretizations/grids/cartesian/rules/cartesian_construction.esm`
expresses this construction as a semiring-FAQ document (RFC `semiring-faq-unified-ir`
§5.1/§5.2: cartesian interval index-sets + elementwise `arrayop` bodies — the M1
path, NO value-invention, all CONST cadence). It is the structured-grid analogue of
`discretizations/grids/duo/rules/primal_topology.esm` (the M3 value-invention path
in `src/topology_faq.jl`).

This module is the thin **evaluation bridge**: it shapes a `CartesianGrid` into the
per-axis elementwise inputs and routes every piece of grid ARITHMETIC — the affine
coordinate map, the cell-center/width derivations, the cell-volume product — through
ESS's AST evaluator (`eval_coeff`, the single pathway in `src/rule_eval.jl`). ESD
hosts no shadow evaluator (AGENTS.md single-pathway invariant; GRIDS_API §4.3), so the
determinism contract — and therefore the cross-binding byte-identity of the output —
lives entirely in `EarthSciSerialization` (`CONFORMANCE_SPEC.md` §5.5). The only
ESD-side logic is the *structural* part — the cartesian-product flattening, the
0-sentinel neighbor linearization, the boundary masks, and the identity-metric
constants — exactly as `topology_faq.jl` materializes `edges_on_face` / `cell_neighbors`
structurally while routing the dedup / rank / join through ESS.
"""

# AST nodes mirroring the equation bodies of
# `discretizations/grids/cartesian/rules/cartesian_construction.esm`. Held as module
# consts so the per-element evaluation does not re-allocate the trees; `eval_coeff`
# (src/rule_eval.jl) re-parses each call, the same single pathway the rule catalog uses.
const _CART_DX_NODE = Dict{String, Any}(
    "op" => "/",
    "args" => Any[Dict{String, Any}("op" => "-", "args" => Any["hi", "lo"]), "n"],
)
const _CART_EDGE_NODE = Dict{String, Any}(
    "op" => "+",
    "args" => Any[
        "lo",
        Dict{String, Any}(
            "op" => "*",
            "args" => Any[Dict{String, Any}("op" => "-", "args" => Any["i", 1]), "dx"],
        ),
    ],
)
const _CART_CENTER_NODE = Dict{String, Any}(
    "op" => "/",
    "args" => Any[Dict{String, Any}("op" => "+", "args" => Any["e_lo", "e_hi"]), 2],
)
const _CART_WIDTH_NODE = Dict{String, Any}("op" => "-", "args" => Any["e_hi", "e_lo"])
const _CART_PROD_NODE = Dict{String, Any}("op" => "*", "args" => Any["a", "b"])

"""
    _faq_axis(T, uniform, n, lo, hi, supplied_edges) -> (edges, centers, widths)

Construct one axis's `edges` / `centers` / `widths` via the M1 elementwise FAQ.

A **uniform** axis is generated by the affine map `edges[i] = lo + (i-1)*dx` with
`dx = (hi - lo)/n` (the declarative `cartesian_construction.esm` `edges` equation); a
**non-uniform** axis instead takes `supplied_edges` as DATA (the `.esm` "supplied as
data" branch). In both cases `centers[i] = (edges[i] + edges[i+1])/2` and
`widths[i] = edges[i+1] - edges[i]` are the elementwise midpoint / difference. Every
arithmetic step is evaluated by ESS (`eval_coeff`), so the result is bit-identical to
the other bindings.
"""
function _faq_axis(::Type{T}, uniform::Bool, n::Int, lo::T, hi::T,
        supplied_edges::AbstractVector{T}) where {T <: AbstractFloat}
    edges = Vector{T}(undef, n + 1)
    if uniform
        dx = eval_coeff(_CART_DX_NODE,
            Dict("hi" => Float64(hi), "lo" => Float64(lo), "n" => Float64(n)))
        @inbounds for i in 1:(n + 1)
            edges[i] = T(eval_coeff(_CART_EDGE_NODE,
                Dict("lo" => Float64(lo), "i" => Float64(i), "dx" => dx)))
        end
    else
        @inbounds for i in 1:(n + 1)
            edges[i] = supplied_edges[i]
        end
    end
    centers = Vector{T}(undef, n)
    widths = Vector{T}(undef, n)
    @inbounds for i in 1:n
        b = Dict("e_lo" => Float64(edges[i]), "e_hi" => Float64(edges[i + 1]))
        centers[i] = T(eval_coeff(_CART_CENTER_NODE, b))
        widths[i] = T(eval_coeff(_CART_WIDTH_NODE, b))
    end
    return edges, centers, widths
end

"""
    cartesian_construction_faq(grid::CartesianGrid) -> NamedTuple

Materialize a cartesian grid's full construction — coordinates, identity metric,
neighbor maps and boundary masks — from the declarative M1 elementwise FAQ, evaluating
all arithmetic through the landed ESS AST evaluator. Returns a NamedTuple whose fields
match the imperative `CartesianGrid` trait arrays (`src/grids/cartesian.jl`) so the
conformance harness can assert byte/ULP equality:

- `edges`, `centers`, `widths` :: `NTuple{N,Vector{T}}` — the per-axis 1-D arrays
  (`edges[d][i] = lo + (i-1)*dx` for a uniform axis; supplied data otherwise).
- `cell_centers`, `cell_widths` :: `NTuple{N,Vector{T}}` — per axis, flattened to one
  value per cell in `CartesianIndices(grid.n)` (column-major) order, matching
  `cell_centers(grid, axis)` / `cell_widths(grid, axis)`.
- `cell_volume` :: `Vector{T}` — per-cell measure = product of the axis widths
  (the product routed through ESS), matching `cell_volume(grid)`.
- `neighbor_minus`, `neighbor_plus` :: `NTuple{N,Vector{Int}}` — flattened LINEAR id of
  the offset −1 / +1 axis neighbor with the `0` sentinel for off-grid, matching
  `neighbor_indices(grid, axis, ∓1)`.
- `boundary_lower`, `boundary_upper` :: `NTuple{N,Vector{Bool}}` — first / last cell of
  the axis, matching `boundary_mask(grid, axis, :lower/:upper)`.
- `metric_g`, `metric_ginv`, `coord_jacobian` :: `Array{T,3}` `(nc, N, N)` — the
  Kronecker-delta identity; `metric_dgij_dxk`, `coord_jacobian_second` :: `Array{T,4}`
  `(nc, N, N, N)` — all zeros; `metric_jacobian` :: `Vector{T}` = `cell_volume`.

The coordinate/volume arithmetic rides ESS's determinism contract; the structural
arrays (flattening, neighbor linearization, masks, identity constants) are pure
index logic, the cartesian analogue of the inversion joins materialized structurally
in `primal_topology_faq`.
"""
function cartesian_construction_faq(grid::CartesianGrid{T, N}) where {T, N}
    n = grid.n
    nc = prod(n)

    # --- per-axis elementwise FAQ (affine coords / centers / widths) ------------
    ax_edges = Vector{Vector{T}}(undef, N)
    ax_centers = Vector{Vector{T}}(undef, N)
    ax_widths = Vector{Vector{T}}(undef, N)
    for d in 1:N
        lo, hi = grid.extent[d]
        e, c, w = _faq_axis(T, grid.uniform[d], n[d], T(lo), T(hi), grid.edges[d])
        ax_edges[d] = e
        ax_centers[d] = c
        ax_widths[d] = w
    end

    ci = CartesianIndices(n)
    li = LinearIndices(n)

    # --- per-cell flattened coordinate gathers (cartesian-product structure) -----
    cell_centers = ntuple(d -> T[ax_centers[d][ci[k][d]] for k in 1:nc], N)
    cell_widths = ntuple(d -> T[ax_widths[d][ci[k][d]] for k in 1:nc], N)

    # --- cell_volume = ∏_d widths_d, the product routed through ESS --------------
    cell_volume = Vector{T}(undef, nc)
    @inbounds for k in 1:nc
        v = Float64(cell_widths[1][k])
        for d in 2:N
            v = eval_coeff(_CART_PROD_NODE, Dict("a" => v, "b" => Float64(cell_widths[d][k])))
        end
        cell_volume[k] = T(v)
    end

    # --- neighbor maps (0-sentinel, flattened linear ids) -----------------------
    _neighbors(offset) = ntuple(N) do d
        out = Vector{Int}(undef, nc)
        nd = n[d]
        @inbounds for k in 1:nc
            ix = ci[k]
            new_d = ix[d] + offset
            if 1 <= new_d <= nd
                out[k] = li[CartesianIndex(ntuple(p -> p == d ? new_d : ix[p], N))]
            else
                out[k] = 0
            end
        end
        out
    end
    neighbor_minus = _neighbors(-1)
    neighbor_plus = _neighbors(+1)

    # --- boundary masks ---------------------------------------------------------
    boundary_lower = ntuple(d -> Bool[ci[k][d] == 1 for k in 1:nc], N)
    boundary_upper = ntuple(d -> Bool[ci[k][d] == n[d] for k in 1:nc], N)

    # --- identity metric + vanishing derivatives --------------------------------
    metric_g = zeros(T, nc, N, N)
    metric_ginv = zeros(T, nc, N, N)
    coord_jac = zeros(T, nc, N, N)
    @inbounds for k in 1:nc, d in 1:N
        metric_g[k, d, d] = one(T)
        metric_ginv[k, d, d] = one(T)
        coord_jac[k, d, d] = one(T)
    end
    metric_jacobian = copy(cell_volume)
    metric_dgij_dxk = zeros(T, nc, N, N, N)
    coord_jac_second = zeros(T, nc, N, N, N)

    return (
        edges = ntuple(d -> ax_edges[d], N),
        centers = ntuple(d -> ax_centers[d], N),
        widths = ntuple(d -> ax_widths[d], N),
        cell_centers = cell_centers,
        cell_widths = cell_widths,
        cell_volume = cell_volume,
        neighbor_minus = neighbor_minus,
        neighbor_plus = neighbor_plus,
        boundary_lower = boundary_lower,
        boundary_upper = boundary_upper,
        metric_g = metric_g,
        metric_ginv = metric_ginv,
        metric_jacobian = metric_jacobian,
        metric_dgij_dxk = metric_dgij_dxk,
        coord_jacobian = coord_jac,
        coord_jacobian_second = coord_jac_second,
    )
end
